name: CI/CD Pipeline to EC2

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "No tests found"

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            if [ ! -d "~/app" ]; then
              git clone  https://github.com/kanchanshewale/CI-CD_Deployment.git ~/app
            fi
            cd ~/app
            git pull origin main
            docker build -t my-nodejs-app .
            docker stop myapp || true
            docker rm myapp || true
            docker run -d -p 80:3000 --name myapp my-nodejs-app

